#!/usr/bin/env bash
# scripts/setup-labels.sh — create GitHub labels required by the pipeline
# Run once: bash scripts/setup-labels.sh

set -euo pipefail
REPO="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"

label() {
  local name="$1" color="$2" desc="$3"
  if gh label list --repo "$REPO" --json name -q '.[].name' | grep -q "^${name}$"; then
    echo "  exists:  $name"
  else
    gh label create "$name" --repo "$REPO" --color "$color" --description "$desc"
    echo "  created: $name"
  fi
}

echo "Setting up labels for $REPO"
label "no-autofix"            "E4E669" "Disables Claude Code auto-fix for this PR"
label "needs-human"           "D93F0B" "Claude escalated — human review required"
label "claude-generated"      "0075CA" "Code generated by Claude Code"
label "requirement-validated" "0E8A16" "Spec validated by tf-requirement agent"
label "needs-analysis"        "FBCA04" "Awaiting tf-requirement agent"
label "ready-for-review"      "0075CA" "Implementation ready for review"
label "awaiting-approval"     "FBCA04" "Awaiting human approval"
echo "Done."
